[package]
name = "sprite-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = { version = "0.32.1", default-features = true }
winit = { version = "0.29.15", default-features = false }

imgui = "0.10"
imgui-glium-renderer = "0.10"
imgui-winit-support = "0.10"
